version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres.api-spring-boot
    hostname: postgres.api-spring-boot
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres/data:/var/lib/postgresql/data

  api:
    image: api-spring-boot:latest
    container_name: api.api-spring-boot
    hostname: api.api-spring-boot
    env_file:
      - ./api-spring-boot-backend.env
    ports:
      - "8080:8080"