version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres.esg-token
    hostname: postgres.esg-token
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres/data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak.esg-token
    hostname: keycloak.esg-token
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres.esg-token
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8090:8080
    depends_on:
      - postgres

  api:
    image: esg-token-backend:latest
    container_name: api.esg-token
    hostname: api.esg-token
    env_file:
      - ./esg-token-backend.env
    ports:
      - "8080:8080"