version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres.esg-token
    hostname: postgres.esg-token
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres/data:/var/lib/postgresql/data

  api:
    image: esg-token-backend:latest
    container_name: api.esg-token
    hostname: api.esg-token
    env_file:
      - ./esg-token-backend.env
    ports:
      - "8080:8080"